version: '3'
services:
  redis:
    image: redis:4-alpine
    ports:
      - '6379:6379'
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    ports:
      - '3306:3306'
